adafactor: false
adam_epsilon: 1.0e-08
cache_dir: null
config_name: null
custom_model_name: multitask
data_dir: glue/mrpc
device: cuda:0
do_train: true
dropout: 0.0
eval_batch_size: 10
eval_beams: 3
eval_max_gen_length: 10
eval_steps: 50
gpus: 1
gradient_accumulation_steps: 1
label_smoothing: 0.0
learning_rate: 5.0e-05
length_penalty: 1.0
lr_scheduler: linear
max_source_length: 10
max_steps: 400
max_target_length: 10
max_tokens_per_batch: null
model_mode: sequence-classification
model_name_or_path: bert-base-cased
n_test: -1
n_train: -1
n_val: 500
num_labels: 1
num_train_epochs: 5
num_workers: 4
output_dir: null
seed: 101
sortish_sampler: false
src_lang: ''
task: mrpc
test_max_target_length: 10
tgt_lang: ''
tokenizer_name: facebook/bart-large
train_batch_size: 10
use_big: false
use_dropout: 'no'
val_max_target_length: 10
val_metric: accuracy
warmup_steps: 100
weight_decay: 0.0
